// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDiary.Data;

#nullable disable

namespace MYDIARY.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250401231553_AddedSeedingDataDiaryEntry")]
    partial class AddedSeedingDataDiaryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MYDIARY.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Went on a long walk with Jenn.",
                            CreatedAt = new DateTime(2024, 3, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Went on a walk"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Bake some double chocolate brownies.",
                            CreatedAt = new DateTime(2024, 3, 25, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Baked brownies"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Went for movies with Jenn.",
                            CreatedAt = new DateTime(2024, 4, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Went for movies"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
